[project]
name = "docker-lightrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gunicorn>=23.0.0",
    "lightrag-hku[api]>=1.3.6",
    "neo4j>=5.28.1",
    "psutil>=7.0.0",
]
