---
name: build

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'Dockerfile'
      - 'requirements.txt'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64,linux/amd64
          push: false
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
